name: PMON Compile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install -y flex bison xutils-dev
    - name: Download toolchain
      run: wget -O /tmp/gcc-4.4.0-pmon.tgz http://ftp.loongnix.org/toolchain/gcc/release/CROSS_COMPILE/gcc-4.4.0-pmon.tgz
    - name: Install toolchain
      run: sudo tar -zxvf /tmp/gcc-4.4.0-pmon.tgz -C /opt/

    - name: Compile and install pmoncfg
      run: cd tools/pmoncfg && make && sudo cp pmoncfg /opt/gcc-4.4.0-pmon/bin/

    - name: Setup env
      run: echo "::add-path::/opt/gcc-4.4.0-pmon/bin" && echo "::set-env name=LD_LIBRARY_PATH::/opt/gcc-4.4.0-pmon/lib:"
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Compile ls2k
      run: cd zloader.ls2k && make cfg && make tgt=rom && cd ..
    - name: Upload ls2k
      uses: actions/upload-artifact@v2
      with:
        name: pmon-ls2k.bin
        path: zloader/gzrom.bin
